In [ ]:
!git clone https://github.com/mateenyaqoob/unstructuredata_tfidf_repo.git

fatal: destination path 'unstructuredata_tfidf_repo' already exists and is not an empty directory.

In [ ]:
import sys
import os
sys.path.append('/content/unstructuredata_tfidf_repo')

In [ ]:
from data import documents

In [ ]:
import nltk
nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')

from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [ ]:
import os

# Check karein ke file mojood hai ya nahi aur usay direct read karein
file_path = 'unstructuredata_tfidf_repo/data/documents.py'

if os.path.exists(file_path):
    with open(file_path, 'r', encoding='utf-8') as f:
        content = f.read()
    print("--- File ka Data ---")
    print(content)
else:
    print("File nahi mili! Yeh check karne ke liye folders list karein:")
    !ls -R unstructuredata_tfidf_repo

--- File ka Data ---
"""Dataset: 10 long-text documents for the TF-IDF class activity."""

TITLES = [
    "AI in Healthcare",
    "Climate Change",
    "Basketball Strategy",
    "Italian Pasta",
    "Space Exploration",
    "Cybersecurity",
    "Music Theory",
    "Gardening Vegetables",
    "Economics Inflation",
    "Public Health",
]

DOCUMENTS = [
    """Artificial intelligence is transforming healthcare by helping doctors analyze medical images, predict disease risk, and personalize treatments. Machine learning models can scan thousands of patient records to find patterns that humans might miss. Hospitals use AI to reduce waiting times and improve diagnosis accuracy. However, AI systems require large, clean datasets and careful validation before clinical use. Privacy, bias, and accountability are major concerns. If used responsibly, AI can support clinicians rather than replace them, making healthcare faster, safer, and more equitable for diverse populations.""",

    """Climate change is driven by greenhouse gas emissions from burning fossil fuels. Renewable energy sources such as solar, wind, and hydropower can reduce carbon pollution. Governments and businesses are investing in batteries, smart grids, and energy efficiency. Communities also need adaptation plans for heat waves, floods, and droughts. Climate policy involves trade-offs between economic growth and environmental protection. Individual actions matter, but large-scale systemic change is essential. Accurate data and international cooperation help track progress toward lowering emissions and limiting global temperature rise.""",

    """Basketball strategy depends on spacing, passing, and player movement. Coaches design plays to create open shots and mismatches. Offenses use pick-and-rolls, screens, and fast breaks, while defenses switch, trap, or zone. Analytics now influences decisions about shot selection, lineup combinations, and pace. A team with strong chemistry often outperforms a group of individual stars. Rebounding and turnovers frequently decide close games. Effective communication on defense is as important as scoring ability. Successful teams practice repeatedly and adjust tactics based on opponent weaknesses and game situations.""",

    """Italian pasta cooking begins with quality ingredients and simple techniques. A good sauce balances tomatoes, olive oil, garlic, herbs, and sometimes meat or cheese. Pasta should be cooked in salted water until al dente, then finished in the sauce for better flavor. Fresh basil and parmesan add aroma and richness. Different shapes suit different sauces: long pasta for light sauces, short tubes for chunky sauces. Regional traditions vary widely across Italy. Home cooks can improve by tasting, seasoning gradually, and respecting the pasta's texture rather than relying only on a timer.""",

    """Space exploration has advanced through robotic missions and human spaceflight. Mars rovers study geology, atmosphere, and signs of ancient water. Telescopes observe distant galaxies, exoplanets, and black holes. Space agencies and private companies are developing reusable rockets to lower launch costs. Astronauts face radiation, isolation, and microgravity health risks. Future missions may establish lunar bases or send crews to Mars. International collaboration and data sharing accelerate discovery. Exploring space also produces technologies that benefit life on Earth, from satellite navigation to medical devices and materials science.""",

    """Cybersecurity protects computers, networks, and personal data from attacks. Common threats include phishing emails, malware, ransomware, and weak passwords. Multi-factor authentication and regular software updates reduce risk. Organizations use firewalls, encryption, and monitoring systems to detect intrusions. Employees are often the weakest link, so security training is essential. Data breaches can damage finances and reputation. Strong cybersecurity requires layered defenses, incident response plans, and privacy laws. As attackers become more sophisticated, defenders must continuously learn new tools, share threat intelligence, and design systems that are secure by default.""",

    """Music theory explains scales, chords, rhythm, and harmony. Musicians practice intervals, chord progressions, and ear training to perform and compose. Different genres use distinct rhythms and instrumentation. A melody becomes memorable through repetition, contrast, and tension. Improvisation requires both theoretical knowledge and listening skills. Recording software allows artists to edit, mix, and produce tracks at home. Live performance depends on timing, dynamics, and communication with bandmates. Learning music improves memory, coordination, and emotional expression. Consistent practice, feedback, and experimentation help musicians develop a personal style over time.""",

    """Gardening vegetables requires healthy soil, sunlight, water, and patience. Compost adds nutrients and improves soil structure. Gardeners rotate crops to prevent pests and diseases. Tomatoes, peppers, beans, and lettuce grow well in many home gardens. Mulch conserves moisture and reduces weeds. Raised beds help control drainage and soil quality. Pests can be managed with beneficial insects, companion planting, and careful monitoring. Harvesting at the right time improves flavor and nutrition. A successful garden depends on observing local climate, planning seasons, and learning from each growing cycle year after year.""",

    """Economics studies how people, firms, and governments allocate scarce resources. Inflation measures the rising cost of goods and services over time. Central banks adjust interest rates to influence borrowing, spending, and investment. High inflation reduces purchasing power, especially for low-income households. Unemployment and economic growth are key indicators of national health. Fiscal policy involves taxation and government spending. Global trade, supply chains, and energy prices affect local economies. Understanding incentives, markets, and data helps policymakers design stable policies. Economic decisions always involve trade-offs between efficiency, equity, and long-term sustainability.""",

    """Public health focuses on preventing disease and improving community well-being. Sleep, exercise, and nutrition strongly influence physical and mental health. Regular activity strengthens the heart, muscles, and immune system. A balanced diet includes vegetables, fruits, whole grains, and protein. Chronic stress can harm sleep, mood, and metabolism. Vaccination, clean water, and health education reduce illness. Public health campaigns encourage healthy habits and early screening. Access to care and social support also shape outcomes. Small daily choices, supportive environments, and evidence-based policies can help populations live longer, healthier, and more productive lives."""
]

In [ ]:
import os
import nltk
from collections import Counter

In [ ]:
nltk.download('punkt', quiet=True)
nltk.download('punkt_tab', quiet=True)
nltk.download('stopwords', quiet=True)

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [ ]:
file_path = 'unstructuredata_tfidf_repo/data/documents.py'
if not os.path.exists(file_path):
    !git clone https://github.com/mateenyaqoob/unstructuredata_tfidf_repo.git

with open(file_path, 'r', encoding='utf-8') as f:
    file_content = f.read()

In [ ]:
tokens = word_tokenize(file_content.lower())

In [ ]:
stop_words = set(stopwords.words('english'))

removed_stopwords = []
clean_tokens = []

In [ ]:
for token in tokens:
    # Sirf alphabetic words check karein
    if token.isalpha():
        if token in stop_words:
            removed_stopwords.append(token)
        else:
            clean_tokens.append(token)

In [ ]:
import os
import nltk
from collections import Counter

# 1. NLTK required packages download karein
nltk.download('punkt', quiet=True)
nltk.download('punkt_tab', quiet=True)
nltk.download('stopwords', quiet=True)

from nltk.tokenize import word_tokenize

# 2. Agar repo clone nahi hui toh clone karein
file_path = 'unstructuredata_tfidf_repo/data/documents.py'
if not os.path.exists('unstructuredata_tfidf_repo'):
    !git clone https://github.com/mateenyaqoob/unstructuredata_tfidf_repo.git

# 3. documents.py se data import karne ke liye path set karein
import sys
sys.path.append('unstructuredata_tfidf_repo')

# 4. documents import karein (repo ke andar jo list hai)
from data.documents import DOCUMENTS

# 5. Har document mein "and" ki frequency check karna
total_and_count = 0

print("--- Document-wise 'and' Count ---")
for i, doc in enumerate(DOCUMENTS):
    # Words tokenize karna aur lowercase banana
    tokens = word_tokenize(doc.lower())

    # Sirf exact word "and" ko count karna (punctuation ya dusray words mix na hon)
    doc_and_count = tokens.count('and')
    total_and_count += doc_and_count

    print(f"Document {i+1}: {doc_and_count} times")

print("\n--------------------------------")
print(f"Total 'and' count in all documents: {total_and_count}")
print("--------------------------------")

--- Document-wise 'and' Count ---
Document 1: 5 times
Document 2: 7 times
Document 3: 7 times
Document 4: 5 times
Document 5: 7 times
Document 6: 7 times
Document 7: 10 times
Document 8: 9 times
Document 9: 8 times
Document 10: 11 times

--------------------------------
Total 'and' count in all documents: 76
--------------------------------

In [28]:
import os
import sys
import nltk
from collections import Counter

# 1. NLTK required packages download karein
nltk.download('punkt', quiet=True)
nltk.download('punkt_tab', quiet=True)
nltk.download('stopwords', quiet=True)

from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

# 2. Agar repo clone nahi hui toh clone karein
if not os.path.exists('unstructuredata_tfidf_repo'):
    !git clone https://github.com/mateenyaqoob/unstructuredata_tfidf_repo.git

# 3. Path set kar ke documents import karein
sys.path.append('unstructuredata_tfidf_repo')
from data.documents import DOCUMENTS

# 4. NLTK ke English stopwords ka set lein
stop_words = set(stopwords.words('english'))

all_removed_stopwords = []

# 5. Har document ko tokenize kar ke sirf stopwords extract karein
for doc in DOCUMENTS:
    tokens = word_tokenize(doc.lower())
    # Sirf woh tokens rakhein jo alphabetic hon aur stopwords ki list mein mojood hon
    doc_stopwords = [word for word in tokens if word.isalpha() and word in stop_words]
    all_removed_stopwords.extend(doc_stopwords)

# 6. Counter use kar ke har stopword ki frequency nikal lein
stopword_counts = Counter(all_removed_stopwords)

print("=== ALL STOPWORDS & THEIR FREQUENCIES ===")
print(f"Total Stopwords Found Across All Documents: {len(all_removed_stopwords)}\n")

# Sab se zyada aane wale stopwords pehle print honge (most common order)
for word, freq in stopword_counts.most_common():
    print(f"'{word}': {freq} times")

=== ALL STOPWORDS & THEIR FREQUENCIES ===
Total Stopwords Found Across All Documents: 199

'and': 76 times
'to': 12 times
'can': 8 times
'on': 8 times
'a': 8 times
'are': 6 times
'for': 6 times
'the': 6 times
'is': 5 times
'of': 5 times
'by': 4 times
'from': 4 times
'as': 4 times
'in': 4 times
'with': 4 times
'that': 3 times
'more': 3 times
'or': 3 times
'than': 2 times
'between': 2 times
'be': 2 times
'through': 2 times
'at': 2 times
'over': 2 times
'before': 1 times
'if': 1 times
'them': 1 times
'such': 1 times
'but': 1 times
'while': 1 times
'now': 1 times
'about': 1 times
'should': 1 times
'until': 1 times
'then': 1 times
'only': 1 times
'has': 1 times
'so': 1 times
'both': 1 times
'each': 1 times
'after': 1 times
'how': 1 times

In [29]:
import os
import sys
from sklearn.feature_extraction.text import TfidfVectorizer

# 1. Agar repo clone nahi hui toh clone karein
if not os.path.exists('unstructuredata_tfidf_repo'):
    !git clone https://github.com/mateenyaqoob/unstructuredata_tfidf_repo.git

# 2. Path set kar ke documents import karein
sys.path.append('unstructuredata_tfidf_repo')
from data.documents import DOCUMENTS

# 3. TfidfVectorizer initialize karein aur stop_words="english" set karein
vectorizer = TfidfVectorizer(stop_words='english')

# 4. Documents par fit aur transform karein
tfidf_matrix = vectorizer.fit_transform(DOCUMENTS)

# 5. Matrix ki shape aur vocabulary size print karein
print("Matrix Shape (Expected: (10, n_unique_terms)):", tfidf_matrix.shape)
print("Vocabulary Size:", len(vectorizer.get_feature_names_out()))

Matrix Shape (Expected: (10, n_unique_terms)): (10, 537)
Vocabulary Size: 537

In [33]:
import os
import sys
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer

# 1. Agar repo clone nahi hui toh clone karein
if not os.path.exists('unstructuredata_tfidf_repo'):
    !git clone https://github.com/mateenyaqoob/unstructuredata_tfidf_repo.git

# 2. Path set kar ke documents import karein
sys.path.append('unstructuredata_tfidf_repo')
from data.documents import DOCUMENTS

# 3. Document titles/names define karein (Index ke liye)
doc_titles = [
    "Doc 1: AI Healthcare",
    "Doc 2: Climate Change",
    "Doc 3: Basketball",
    "Doc 4: Italian Pasta",
    "Doc 5: Space Exploration",
    "Doc 6: Cybersecurity",
    "Doc 7: Music Theory",
    "Doc 8: Gardening",
    "Doc 9: Economics",
    "Doc 10: Public Health"
]

# 4. TfidfVectorizer fit aur transform karein
vectorizer = TfidfVectorizer(stop_words='english')
tfidf_matrix = vectorizer.fit_transform(DOCUMENTS)

# 5. Sparse matrix ko Pandas DataFrame mein convert karna
df_tfidf = pd.DataFrame(
    tfidf_matrix.toarray(),
    index=doc_titles,
    columns=vectorizer.get_feature_names_out()
)

print("=== 1. Sample of the Matrix (First 3 Documents × First 10 Terms) ===")
# Displaying first 3 rows and first 10 columns
display(df_tfidf.iloc[:, :10])
print("\n" + "="*60 + "\n")

print("=== 2. Top-5 TF-IDF Terms for Each Document (Summary) ===")
feature_names = np.array(vectorizer.get_feature_names_out())

for i, title in enumerate(doc_titles):
    # Har document ke scores nikalna
    row_scores = tfidf_matrix.toarray()[i]

    # Sab se baray 5 scores ke indices nikalna (descending order mein)
    top_n_indices = row_scores.argsort()[::-1][:5]

    # Terms aur unke scores print karna
    top_terms = [(feature_names[idx], round(row_scores[idx], 4)) for idx in top_n_indices]

    print(f"\n{title}:")
    for term, score in top_terms:
        print(f"   - {term}: {score}")

=== 1. Sample of the Matrix (First 3 Documents × First 10 Terms) ===

,ability,accelerate,access,accountability,accuracy,accurate,actions,activity,adaptation,add
Doc 1: AI Healthcare,0.000000,0.000000,0.000000,0.1246,0.1246,0.000000,0.000000,0.000000,0.000000,0.000000
Doc 2: Climate Change,0.000000,0.000000,0.000000,0.0000,0.0000,0.124795,0.124795,0.000000,0.124795,0.000000
Doc 3: Basketball,0.130137,0.000000,0.000000,0.0000,0.0000,0.000000,0.000000,0.000000,0.000000,0.000000
Doc 4: Italian Pasta,0.000000,0.000000,0.000000,0.0000,0.0000,0.000000,0.000000,0.000000,0.000000,0.110774
Doc 5: Space Exploration,0.000000,0.116348,0.000000,0.0000,0.0000,0.000000,0.000000,0.000000,0.000000,0.000000
Doc 6: Cybersecurity,0.000000,0.000000,0.000000,0.0000,0.0000,0.000000,0.000000,0.000000,0.000000,0.000000
Doc 7: Music Theory,0.000000,0.000000,0.000000,0.0000,0.0000,0.000000,0.000000,0.000000,0.000000,0.000000
Doc 8: Gardening,0.000000,0.000000,0.000000,0.0000,0.0000,0.000000,0.000000,0.000000,0.000000,0.000000
Doc 9: Economics,0.000000,0.000000,0.000000,0.0000,0.0000,0.000000,0.000000,0.000000,0.000000,0.000000
Doc 10: Public Health,0.000000,0.000000,0.116379,0.0000,0.0000,0.000000,0.000000,0.116379,0.000000,0.000000

============================================================

=== 2. Top-5 TF-IDF Terms for Each Document (Summary) ===

Doc 1: AI Healthcare:
   - ai: 0.3738
   - healthcare: 0.2492
   - use: 0.1648
   - treatments: 0.1246
   - times: 0.1246

Doc 2: Climate Change:
   - emissions: 0.2496
   - change: 0.2496
   - energy: 0.2122
   - climate: 0.2122
   - fuels: 0.1248

Doc 3: Basketball:
   - stars: 0.1301
   - strategy: 0.1301
   - pace: 0.1301
   - mismatches: 0.1301
   - create: 0.1301

Doc 4: Italian Pasta:
   - pasta: 0.4431
   - sauces: 0.3323
   - sauce: 0.2215
   - different: 0.1883
   - traditions: 0.1108

Doc 5: Space Exploration:
   - space: 0.349
   - mars: 0.2327
   - missions: 0.2327
   - benefit: 0.1163
   - ancient: 0.1163

Doc 6: Cybersecurity:
   - cybersecurity: 0.2494
   - systems: 0.212
   - data: 0.1649
   - link: 0.1247
   - tools: 0.1247

Doc 7: Music Theory:
   - musicians: 0.247
   - music: 0.247
   - practice: 0.2099
   - memorable: 0.1235
   - melody: 0.1235

Doc 8: Gardening:
   - soil: 0.3581
   - pests: 0.2387
   - year: 0.2387
   - improves: 0.2029
   - beneficial: 0.1194

Doc 9: Economics:
   - spending: 0.2345
   - inflation: 0.2345
   - trade: 0.1994
   - economic: 0.1994
   - prices: 0.1173

Doc 10: Public Health:
   - health: 0.3462
   - public: 0.2328
   - sleep: 0.2328
   - strongly: 0.1164
   - physical: 0.1164

In [35]:
import os
import sys
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer

# 1. Agar repo clone nahi hui toh clone karein
if not os.path.exists('unstructuredata_tfidf_repo'):
    !git clone https://github.com/mateenyaqoob/unstructuredata_tfidf_repo.git

# 2. Path set kar ke documents import karein
sys.path.append('unstructuredata_tfidf_repo')
from data.documents import DOCUMENTS

# 3. Document titles define karein
doc_titles = [
    "Doc 1: AI Healthcare",
    "Doc 2: Climate Change",
    "Doc 3: Basketball",
    "Doc 4: Italian Pasta",
    "Doc 5: Space Exploration",
    "Doc 6: Cybersecurity",
    "Doc 7: Music Theory",
    "Doc 8: Gardening",
    "Doc 9: Economics",
    "Doc 10: Public Health"
]

# 4. TfidfVectorizer fit aur transform karein
vectorizer = TfidfVectorizer(stop_words='english')
tfidf_matrix = vectorizer.fit_transform(DOCUMENTS)

# 5. Pandas options set karna taake poora matrix screen par properly dikhe
pd.set_option('display.max_rows', None)        # Saari rows (10 documents) dikhane ke liye
pd.set_option('display.max_columns', None)     # Saare columns (terms) dikhane ke liye
pd.set_option('display.width', 1000)           # Width adjust karne ke liye
pd.set_option('display.float_format', lambda x: '%.4f' % x) # Decimal values ko 4 places tak round off karna

# 6. DataFrame banana aur display karna
df_tfidf_full = pd.DataFrame(
    tfidf_matrix.toarray(),
    index=doc_titles,
    columns=vectorizer.get_feature_names_out()
)

print("=== COMPLETE TF-IDF MATRIX ===")
display(df_tfidf_full)

=== COMPLETE TF-IDF MATRIX ===

,ability,accelerate,access,accountability,accuracy,accurate,actions,activity,adaptation,add,adds,adjust,advanced,affect,agencies,ai,al,allocate,allows,analytics,analyze,ancient,aroma,artificial,artists,astronauts,atmosphere,attackers,attacks,authentication,balanced,balances,bandmates,banks,based,bases,basil,basketball,batteries,beans,beds,begins,beneficial,benefit,better,bias,black,borrowing,breaches,breaks,burning,businesses,campaigns,carbon,care,careful,central,chains,change,cheese,chemistry,choices,chord,chords,chronic,chunky,clean,climate,clinical,clinicians,close,coaches,collaboration,combinations,common,communication,communities,community,companies,companion,compose,compost,computers,concerns,conserves,consistent,continuously,contrast,control,cooked,cooking,cooks,cooperation,coordination,cost,costs,create,crews,crops,cybersecurity,cycle,daily,damage,data,datasets,decide,decisions,default,defenders,defense,defenses,dente,depends,design,detect,develop,developing,devices,diagnosis,diet,different,discovery,disease,diseases,distant,distinct,diverse,doctors,drainage,driven,droughts,dynamics,ear,early,earth,economic,economics,economies,edit,education,effective,efficiency,emails,emissions,emotional,employees,encourage,encryption,energy,environmental,environments,equitable,equity,especially,essential,establish,evidence,exercise,exoplanets,experimentation,explains,exploration,exploring,expression,face,factor,fast,faster,feedback,finances,finished,firewalls,firms,fiscal,flavor,floods,focuses,fossil,frequently,fresh,fruits,fuels,future,galaxies,game,games,garden,gardeners,gardening,gardens,garlic,gas,genres,geology,global,good,goods,government,governments,gradually,grains,greenhouse,grids,group,grow,growing,growth,habits,harm,harmony,harvesting,health,healthcare,healthier,healthy,heart,heat,help,helping,helps,herbs,high,holes,home,hospitals,households,human,humans,hydropower,illness,images,immune,important,improve,improves,improving,improvisation,incentives,incident,include,includes,income,indicators,individual,inflation,influence,influences,ingredients,insects,instrumentation,intelligence,international,intervals,intrusions,investing,investment,involve,involves,isolation,italian,italy,key,knowledge,large,launch,laws,layered,learn,learning,lettuce,life,light,limiting,lineup,link,listening,live,lives,local,long,longer,low,lower,lowering,lunar,machine,major,making,malware,managed,markets,mars,materials,matter,measures,meat,medical,melody,memorable,memory,mental,metabolism,microgravity,mismatches,miss,missions,mix,models,moisture,monitoring,mood,movement,mulch,multi,muscles,music,musicians,national,navigation,need,networks,new,nutrients,nutrition,observe,observing,offenses,offs,oil,olive,open,opponent,organizations,outcomes,outperforms,pace,parmesan,passing,passwords,pasta,patience,patient,patterns,people,peppers,perform,performance,personal,personalize,pests,phishing,physical,pick,planning,plans,planting,player,plays,policies,policy,policymakers,pollution,populations,power,practice,predict,prevent,preventing,prices,privacy,private,produce,produces,productive,progress,progressions,protection,protects,protein,public,purchasing,quality,radiation,raised,ransomware,rates,rebounding,recording,records,reduce,reduces,regional,regular,relying,renewable,repeatedly,repetition,replace,reputation,require,requires,resources,respecting,response,responsibly,reusable,rhythm,rhythms,richness,right,rise,rising,risk,risks,robotic,rockets,rolls,rotate,rovers,safer,salted,satellite,sauce,sauces,scale,scales,scan,scarce,science,scoring,screening,screens,seasoning,seasons,secure,security,selection,send,services,shape,shapes,share,sharing,short,shot,shots,signs,simple,situations,skills,sleep,small,smart,social,software,soil,solar,sophisticated,sources,space,spaceflight,spacing,spending,stable,stars,strategy,strengthens,stress,strong,strongly,structure,studies,study,style,successful,suit,sunlight,supply,support,supportive,sustainability,switch,systemic,systems,tactics,tasting,taxation,team,teams,techniques,technologies,telescopes,temperature,tension,term,texture,theoretical,theory,thousands,threat,threats,time,timer,times,timing,tomatoes,tools,track,tracks,trade,traditions,training,transforming,trap,treatments,tubes,turnovers,understanding,unemployment,updates,use,used,vaccination,validation,vary,vegetables,waiting,water,waves,weak,weakest,weaknesses,weeds,widely,wind,year,zone
Doc 1: AI Healthcare,0.0000,0.0000,0.0000,0.1246,0.1246,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.3738,0.0000,0.0000,0.0000,0.0000,0.1246,0.0000,0.0000,0.1246,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.1246,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.1059,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.1059,0.0000,0.1246,0.1246,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.1246,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.1246,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.1246,0.0000,0.0000,0.0000,0.1059,0.0000,0.0000,0.0000,0.1246,0.1246,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.1246,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.1246,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.2492,0.0000,0.0000,0.0000,0.0000,0.0000,0.1246,0.0000,0.0000,0.0000,0.0000,0.0000,0.1246,0.0000,0.0000,0.1246,0.0000,0.0000,0.1246,0.0000,0.0000,0.1059,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.1059,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.1059,0.0000,0.0000,0.0000,0.0000,0.0927,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.1246,0.1246,0.1246,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.1059,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.1246,0.0000,0.0000,0.1246,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.1246,0.1246,0.0000,0.0000,0.0000,0.0000,0.0000,0.1246,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.1059,0.0000,0.0000,0.1246,0.0000,0.0000,0.0000,0.1059,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.1246,0.0824,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.1246,0.0000,0.1246,0.0000,0.0000,0.0000,0.0000,0.1246,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.1059,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.1246,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.1246,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.1059,0.0000,0.0000,0.0000,0.0000,0.1059,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.1246,0.0000,0.0000,0.0000,0.0000,0.1246,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.1246,0.0000,0.1246,0.0000,0.0000,0.0000,0.0000,0.0000,0.1648,0.1246,0.0000,0.1246,0.0000,0.0000,0.1246,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
Doc 2: Climate Change,0.0000,0.0000,0.0000,0.0000,0.0000,0.1248,0.1248,0.0000,0.1248,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.1248,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.1248,0.1248,0.0000,0.1248,0.0000,0.0000,0.0000,0.0000,0.2496,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.2122,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.1248,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.1248,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0825,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.1248,0.1248,0.0000,0.0000,0.0000,0.0000,0.1061,0.0000,0.0000,0.0000,0.0000,0.0000,0.1061,0.0000,0.2496,0.0000,0.0000,0.0000,0.0000,0.2122,0.1248,0.0000,0.0000,0.0000,0.0000,0.1061,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.1248,0.0000,0.1248,0.0000,0.0000,0.0000,0.1248,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.1248,0.0000,0.0000,0.1061,0.0000,0.0000,0.0000,0.1061,0.0000,0.0000,0.1248,0.1248,0.0000,0.0000,0.0000,0.1061,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.1248,0.0825,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.1248,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.1061,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.1061,0.0000,0.0000,0.1248,0.0000,0.0000,0.1061,0.0000,0.0000,0.0000,0.0000,0.0000,0.1061,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.1248,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.1248,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.1248,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.1248,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.1061,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.1061,0.0000,0.0000,0.0000,0.0000,0.1061,0.0000,0.1248,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.1248,0.0000,0.1248,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0825,0.0000,0.0000,0.0000,0.0000,0.1248,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.1248,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.1248,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.1248,0.0000,0.0000,0.0000,0.1248,0.0000,0.1248,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.1248,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.1248,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.1248,0.0000,0.1061,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.1248,0.0000,0.0000,0.0000,0.0000,0.0000,0.1248,0.0000,0.0000
Doc 3: Basketball,0.1301,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.1106,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.1301,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.1106,0.0000,0.0000,0.1301,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.1301,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.1301,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.1301,0.1301,0.0000,0.1301,0.0000,0.1106,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.1301,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.1301,0.1106,0.0000,0.0000,0.1301,0.1106,0.0000,0.0968,0.0968,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.1301,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.1301,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.1301,0.0000,0.0000,0.0000,0.0000,0.0000,0.1301,0.1301,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.1301,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.1301,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.1106,0.0000,0.0000,0.1301,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.1301,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.1301,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.1301,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.1301,0.0000,0.0000,0.0000,0.1301,0.1301,0.0000,0.0000,0.1301,0.1301,0.0000,0.1301,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.1301,0.0000,0.0000,0.0000,0.1301,0.1301,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.1106,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.1301,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.1301,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.1301,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.1301,0.0000,0.1301,0.0000,0.0000,0.0000,0.0000,0.1301,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.1301,0.1301,0.0000,0.0000,0.1301,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.1301,0.0000,0.0000,0.1301,0.1301,0.0000,0.0000,0.1106,0.0000,0.0000,0.0000,0.0000,0.0000,0.1106,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.1301,0.0000,0.0000,0.1301,0.0000,0.0000,0.1301,0.1301,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.1301,0.0000,0.0000,0.1301,0.0000,0.0000,0.0000,0.0861,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.1301,0.0000,0.0000,0.0000,0.0000,0.1301
Doc 4: Italian Pasta,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.1108,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.1108,0.0000,0.0000,0.0000,0.0000,0.0000,0.1108,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.1108,0.0000,0.0000,0.0000,0.0000,0.1108,0.0000,0.0000,0.0000,0.0000,0.1108,0.0000,0.0000,0.1108,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.1108,0.0000,0.0000,0.0000,0.0000,0.0000,0.1108,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.1108,0.1108,0.1108,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.1108,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.1883,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.1108,0.0000,0.0000,0.0000,0.0942,0.0000,0.0000,0.0000,0.0000,0.1108,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.1108,0.0000,0.0000,0.0000,0.0000,0.1108,0.0000,0.0000,0.0000,0.1108,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.1108,0.0000,0.0000,0.0824,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0942,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.1108,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.1108,0.1108,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.1108,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0942,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.1108,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.1108,0.1108,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.1108,0.0000,0.0000,0.4431,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0942,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.1108,0.0000,0.1108,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.1108,0.0000,0.0000,0.0000,0.0000,0.0000,0.1108,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.1108,0.0000,0.2215,0.3323,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.1108,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.1108,0.0000,0.0000,0.1108,0.0000,0.0000,0.0000,0.1108,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.1108,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.1108,0.0000,0.0000,0.0000,0.1108,0.0000,0.0000,0.0000,0.0000,0.0000,0.1108,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.1108,0.0000,0.0000,0.0942,0.0000,0.0000,0.0000,0.0000,0.1108,0.0000,0.0000,0.0000,0.0000,0.1108,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.1108,0.0000,0.0000,0.0732,0.0000,0.0000,0.0000,0.0000,0.0000,0.1108,0.0000,0.0000,0.0000

In [36]:
import os
import sys
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# 1. Agar repo clone nahi hui toh clone karein
if not os.path.exists('unstructuredata_tfidf_repo'):
    !git clone https://github.com/mateenyaqoob/unstructuredata_tfidf_repo.git

# 2. Path set kar ke documents import karein
sys.path.append('unstructuredata_tfidf_repo')
from data.documents import DOCUMENTS

# 3. Document titles define karein
doc_titles = [
    "Doc 1: AI Healthcare",
    "Doc 2: Climate Change",
    "Doc 3: Basketball",
    "Doc 4: Italian Pasta",
    "Doc 5: Space Exploration",
    "Doc 6: Cybersecurity",
    "Doc 7: Music Theory",
    "Doc 8: Gardening",
    "Doc 9: Economics",
    "Doc 10: Public Health"
]

# 4. TfidfVectorizer fit aur transform karein (Documents par)
vectorizer = TfidfVectorizer(stop_words='english')
tfidf_matrix = vectorizer.fit_transform(DOCUMENTS)

# 5. Query Similarity Function define karna
def rank_documents_by_query(query, docs, vectorizer, doc_tfidf_matrix, titles):
    # Query ko usi vectorizer ke zariye transform karein (Fit nahi karna, sirf transform!)
    query_vector = vectorizer.transform([query])

    # Cosine similarity calculate karein query aur saare documents ke darmiyan
    similarity_scores = cosine_similarity(query_vector, doc_tfidf_matrix).flatten()

    # Documents ko similarity scores ke lihaz se descending order (highest to lowest) mein rank karein
    ranked_indices = similarity_scores.argsort()[::-1]

    print(f"\n==================================================")
    print(f"QUERY: '{query}'")
    print(f"==================================================")

    for rank, idx in enumerate(ranked_indices, start=1):
        score = similarity_scores[idx]
        print(f"{rank}. {titles[idx]} (Score: {score:.4f})")

# 6. Predefined queries par function run karna
queries = [
    "renewable energy and climate policy",
    "password security and phishing",
    "healthy sleep exercise and diet"
]

for q in queries:
    rank_documents_by_query(q, DOCUMENTS, vectorizer, tfidf_matrix, doc_titles)

==================================================
QUERY: 'renewable energy and climate policy'
==================================================
1. Doc 2: Climate Change (Score: 0.3235)
2. Doc 9: Economics (Score: 0.0952)
3. Doc 8: Gardening (Score: 0.0485)
4. Doc 10: Public Health (Score: 0.0000)
5. Doc 6: Cybersecurity (Score: 0.0000)
6. Doc 7: Music Theory (Score: 0.0000)
7. Doc 5: Space Exploration (Score: 0.0000)
8. Doc 4: Italian Pasta (Score: 0.0000)
9. Doc 3: Basketball (Score: 0.0000)
10. Doc 1: AI Healthcare (Score: 0.0000)

==================================================
QUERY: 'password security and phishing'
==================================================
1. Doc 6: Cybersecurity (Score: 0.1764)
2. Doc 10: Public Health (Score: 0.0000)
3. Doc 9: Economics (Score: 0.0000)
4. Doc 8: Gardening (Score: 0.0000)
5. Doc 7: Music Theory (Score: 0.0000)
6. Doc 5: Space Exploration (Score: 0.0000)
7. Doc 4: Italian Pasta (Score: 0.0000)
8. Doc 3: Basketball (Score: 0.0000)
9. Doc 2: Climate Change (Score: 0.0000)
10. Doc 1: AI Healthcare (Score: 0.0000)

==================================================
QUERY: 'healthy sleep exercise and diet'
==================================================
1. Doc 10: Public Health (Score: 0.2849)
2. Doc 8: Gardening (Score: 0.0447)
3. Doc 9: Economics (Score: 0.0000)
4. Doc 7: Music Theory (Score: 0.0000)
5. Doc 6: Cybersecurity (Score: 0.0000)
6. Doc 5: Space Exploration (Score: 0.0000)
7. Doc 4: Italian Pasta (Score: 0.0000)
8. Doc 3: Basketball (Score: 0.0000)
9. Doc 2: Climate Change (Score: 0.0000)
10. Doc 1: AI Healthcare (Score: 0.0000)